language: python
python:
    - 2.7
    - 3.6
    - 3.8

install:
    pip install codecov
    pip install -U pytest

script:
    pytest

deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "Encrypted <access-key-id>=AKIASYHYQNLOAZ7V4IC2"
  secret_access_key:
    secure: "Encypted <secret-access-key>=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"
  region: "us-east-2"
  app: "CPS847-Assignment-2"
  env: "Cps847assignment2-env"
  bucket_name: "elasticbeanstalk-us-east-2-189499730652"
  on:
    branch: main

after_deploy:
    - echo "deploy complete"