language: python
python:
    - 2.7
    - 3.6
    - 3.8

install:
    pip install codecov
    pip install -U pytest

script:
    pytest

deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "Encrypted <access-key-id>=key-0eccf817ca3a590e1"
  secret_access_key:
    secure: "Encypted <secret-access-key>=5b03e6864a2261f3ffe536e22147e42f0321bbff"
  region: "us-east-2"
  app: "CPS847-Assignment-2"
  env: "Cps847assignment2-env"
  bucket_name: "elasticbeanstalk-us-east-2-189499730652"
  on:
    branch: main

after_deploy:
    - echo "deploy complete"