language: python
python:
    #- 2.7
    #- 3.6
    - 3.8

install:
    pip install codecov
    pip install -U pytest
    pip install coverage

script:
    coverage run test_calculator.py

deploy:
  provider: elasticbeanstalk
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
  region: "us-east-2"
  app: "CPS847-A2"
  env: "Cps847a2-env-1"
  bucket_name: "elasticbeanstalk-us-east-2-189499730652"
  on:
    branch: main

after_deploy:
    - echo "deploy complete"
    - bash <(curl -s https://codecov.io/bash)